//This file contains custom entity utility code autogenerated by Sven Co-op. Sven Co-op includes these automatically for scripts that are allowed to define custom entities.

ScriptClassInterface@ CastToScriptClass(CBaseEntity@ pEntity)
{
	return (g_EntityFuncs.CastToScriptClass(pEntity));
}
